package exporter

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/axelyn/envx/pkg/envx"
)

type Exporter struct{}

func New() *Exporter {
	return &Exporter{}
}

func (e *Exporter) ExportToDotenv(variables map[string]envx.Variable, outputPath string, withComments bool) error {
	keys := make([]string, 0, len(variables))
	for key := range variables {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	var lines []string
	
	if withComments {
		lines = append(lines, "# Generated by envx")
		lines = append(lines, "# https://github.com/aminhaiqal/envx")
		lines = append(lines, "")
	}

	for _, key := range keys {
		variable := variables[key]
		
		if withComments && variable.Description != "" {
			lines = append(lines, fmt.Sprintf("# %s", variable.Description))
		}
		
		value := variable.Value
		
		if strings.ContainsAny(value, " \t\n\r\"'$") {
			value = fmt.Sprintf("\"%s\"", strings.ReplaceAll(value, "\"", "\\\""))
		}
		
		lines = append(lines, fmt.Sprintf("%s=%s", key, value))
		
		if withComments {
			lines = append(lines, "")
		}
	}

	content := strings.Join(lines, "\n")
	
	dir := filepath.Dir(outputPath)
	if dir != "." && dir != "" {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("failed to create directory: %w", err)
		}
	}

	if err := os.WriteFile(outputPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write .env file: %w", err)
	}

	return nil
}

func (e *Exporter) ExportTemplate(variables map[string]envx.Variable, outputPath string) error {
	keys := make([]string, 0, len(variables))
	for key := range variables {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	var lines []string
	lines = append(lines, "# envx template - Fill in your values")
	lines = append(lines, "# Copy this file to .env and update the values")
	lines = append(lines, "")

	for _, key := range keys {
		variable := variables[key]
		
		if variable.Description != "" {
			lines = append(lines, fmt.Sprintf("# %s", variable.Description))
		}
		
		placeholder := "<your-value>"
		if variable.IsSecret {
			placeholder = "<your-secret>"
		}
		
		lines = append(lines, fmt.Sprintf("%s=%s", key, placeholder))
		lines = append(lines, "")
	}

	content := strings.Join(lines, "\n")

	if outputPath == "" {
		fmt.Print(content)
		return nil
	}

	if err := os.WriteFile(outputPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write template file: %w", err)
	}

	return nil
}